-- Query 3 : Calculate Net profit by subtracting losses on unsold items from total profit earned per year.

/* CREATING TEMPORARY TABLE FOR STORES :- */
SELECT SFT.Sales,TD.Year INTO #TEMP_TABLE_STORE_YEARS FROM Store_Sales_Fact_Table SFT INNER JOIN Time_Dim TD ON SFT.Time_ID=TD.Time_ID
SELECT SUM(Sales) AS 'Yearly Sales',Year INTO #TEMP_TABLE_YEARLY_STORE_SALES FROM #TEMP_TABLE_STORE_YEARS GROUP BY Year

/* CREATING TEMPORARY TABLE FOR DISTRIBUTORS :- */
SELECT SFT.Sales,TD.Year INTO #TEMP_TABLE_DISTRIBUTOR_YEARS FROM Distributor_Sales_Fact_Table SFT INNER JOIN Time_Dim TD ON SFT.Time_ID=TD.Time_ID
SELECT SUM(Sales) AS 'Yearly Sales',Year INTO #TEMP_TABLE_YEARLY_DISTRIBUTOR_SALES FROM #TEMP_TABLE_DISTRIBUTOR_YEARS GROUP BY Year

/* CREATING TEMPORARY TABLE FOR SUM :- */
SELECT Year, SUM([Yearly Sales]) AS TotalSales INTO #TEMP_TABLE_YEARLY_TOTAL_SALES
FROM (
    SELECT Year, [Yearly Sales]
    FROM #TEMP_TABLE_YEARLY_DISTRIBUTOR_SALES
    UNION ALL
    SELECT Year, [Yearly Sales]
    FROM #TEMP_TABLE_YEARLY_STORE_SALES
) AS CombinedSales
GROUP BY Year;


/* CREATING TEMPORARY TABLE FOR MANUFACTURING COST :- */
SELECT MFT.Manufacturing_Cost,TD.Year INTO #TEMP_TABLE_COST_YEARS FROM Manufacturing_Fact_Table MFT INNER JOIN Time_Dim TD ON MFT.Time_ID=TD.Time_ID
SELECT SUM(Manufacturing_Cost) AS 'Yearly Cost',Year INTO #TEMP_TABLE_YEARLY_COST FROM #TEMP_TABLE_COST_YEARS GROUP BY Year


SELECT t1.Year, (t1.TotalSales - t2.[Yearly Cost]) AS 'Difference'
FROM #TEMP_TABLE_YEARLY_TOTAL_SALES t1
INNER JOIN #TEMP_TABLE_YEARLY_COST t2 ON t1.Year = t2.Year

